#!/usr/bin/env bash

# Updates entries in packages.json from Spacchetti

for target in $(jq 'keys[]' packages.json -r)
do
  entry=$(jq ".\"$target\"" ../spacchetti/packages.json -r)
  if [[ $entry != 'null' ]]
  then
    jq ".\"$target\" = $entry" packages.json > temp.json
    mv temp.json packages.json
    echo "updated $target"
  else
    echo "doesn't exist in spacchetti: $target"
  fi
done
