name: Update the package set

on:
  pull_request_target:
    branches: master
    paths: "src/**/**.dhall"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PACKAGE_SETS_TOKEN }}

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09

      - name: Generate packages.json file from the package set
        id: generate-packages
        run: |
          nix-shell --run 'make generate'
          echo ::set-output name=modified::$(if git diff --quiet; then echo "false"; else echo "true"; fi)

      - name: Commit and push modified files
        if: steps.generate-packages.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git pull --ff-only
          git commit -am "Update packages.json file"
          git push

      - name: Verify all packages are in the registry
        run: nix-shell --run 'make verify-registry'

      - name: Verify all packages are compatible with psc-package
        run: nix-shell --run 'make test-psc-package'
