name: Update the package set

on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09

      - name: Generate packages.json file from the package set
        id: generate-packages
        run: |
          nix-shell --run 'make generate'
          echo ::set-output name=modified::$(if git diff --quiet; then echo "false"; else echo "true"; fi)

      - name: Commit and push modified files
        if: steps.generate-packages.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git pull --ff-only
          git commit -am "Update packages.json file"
          git push
