name: Update packages.json

on:
  push:
    branches: master

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09

      - name: Generate packages.json file from the package set
        run: nix-shell --run 'make generate'

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff --quiet; then echo "false"; else echo "true"; fi)

      - name: Commit and push modified files
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git pull --ff-only
          git commit -am "Update packages.json file"
          git push
